### ISSUE TITLE
Crash on startup after updating Mekanism to v10

### ISSUE THREAD

**Issue by Sosea1** [sddsd2332/EcoEnergistics#9]
After updating Mekanism CE Unofficial to version 10, the game crashes during startup.

**Error line from the log:** java.lang.NoClassDefFoundError: aeternal/ecoenergistics/common/inventory/container/ContainerEcoSolarGenerator

It looks like Mekanism changed its containers/generators in v10, causing EcoEnergistics to fail when trying to load them.

**Installed mods:**
- **Mekanism EcoEnergistics - Unofficial: v1.5** (mekanismecoenergistics-1.5.jar)
- **Mekanism CE Unofficial: v10.0.0.450** (Mekanism-CE-Unofficial-All-10.0.0.450.jar)

**Crash report**: [crash-2026-07-03_23.27.51-client.txt](https://github.com/user-attachments/files/29644466/crash-2026-07-03_23.27.51-client.txt)
